### ISSUE TITLE
npx -invalid command user:list

### ISSUE THREAD

**Issue by pcs3rd** [os-js/osjs-database-auth#3]
Currently trying to intigrate the database connector for mysql, After installing connector and everything, 
`npx osjs-cli user:list
`  
returns   
```
Invalid command: user:list
See --help for a list of available commands.
```

**Comment by andersevenrud** [comment]
Did you add the stuff from the README into your `src/cli/index.js` file ?

**Comment by pcs3rd** [comment]
yes. This is my index file
```
// In the top of the file load the library
const dbAuth = require('@osjs/database-auth');

// Create a database authentication instance
const dbCli = dbAuth.cli({
  // Change this to match your local database server
  type: 'mysql',
  host: 'localhost',
  username: 'osjs',
  password: 'secret',
  database: 'osjsv3',

  // See TypeORM documentation for more settings
});

// Then finally add 'dbCli' to the tasks array
module.exports = {
  discover: [],
  tasks: [dbCli]
};


```

**Comment by andersevenrud** [comment]
That's the entirety of the file ?

What's the output of `npx osjs-cli` ?

**Comment by pcs3rd** [comment]
Minus the comments at the top.
```
$npx osjs-cli
Usage:  [options] [command]

Options:
  -V, --version               output the version number
  --dist [dist]               Target dist directory ('dist/' by default)
  -h, --help                  output usage information

Commands:
  make:auth                   Create Authentication adapter script
  make:settings               Create Settings adapter script
  make:provider               Create Service provider script
  make:vfs                    Create VFS adapter script
  make:application            Create Application package
  make:iframe-application     Create IFrame Application package
  create:package              [deprecated] Creates a new package
  package:discover [options]  Discovers all installed OS.js packages
  watch:all                   Watch all linked node packages

More information:
- https://manual.os-js.org/v3/guide/cli/
```

**Comment by andersevenrud** [comment]
Doesn't seem like the tasks were loaded, which is a bit strange if your CLI index file is exactly like you pasted above. I've tried a couple of methods to reproduce this, but it looks like everything is OK.

Is there a way I can look at your installation? Like TeamViewer or something.

**Comment by andersevenrud** [comment]
If you update `@osjs/cli` (`npm update @osjs/cli`) you can now run the following task to dump some information about the installation and CLI, which might be helpful in debugging this:

`npx osjs-cli info`

**Comment by pcs3rd** [comment]
@andersevenrud, os.js is running headless. I can give a ssh session the will idle for about half an hour before it closes. Im currently not home at the moment

**Comment by pcs3rd** [comment]
```
osjs@server:~/OS.js $ npx osjs-cli info

00:30:39  WARN  An error occured while loading cli config


00:30:39  FATAL  SyntaxError: Identifier 'dbAuth' has already been declared

  at cli (node_modules/@osjs/cli/src/cli.js:119:21)
  at Object.<anonymous> (node_modules/@osjs/cli/bin/cli.js:35:1)
  at Module._compile (module.js:653:30)
  at Object.Module._extensions..js (module.js:664:10)
  at Module.load (module.js:566:32)
  at tryModuleLoad (module.js:506:12)
  at Function.Module._load (module.js:498:3)
  at Function.Module.runMain (module.js:694:10)
  at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
  at <anonymous>

(node:26941) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at loadTasks (/home/osjs/OS.js/node_modules/@osjs/cli/src/cli.js:51:29)
    at cli (/home/osjs/OS.js/node_modules/@osjs/cli/src/cli.js:123:10)
    at Object.<anonymous> (/home/osjs/OS.js/node_modules/@osjs/cli/bin/cli.js:35:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
(node:26941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26941) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by andersevenrud** [comment]
Something tells me that this comes from your index.js file. Are you on the Gitter community chat ? That's probably the easiest way to negotiate a way for me to have a look.

**Comment by pcs3rd** [comment]
That sounds like a plan, I won't be able to chat until about 2:30 EST

**Comment by andersevenrud** [comment]
If my calculations are correct that should work. I'm in CEST (UTC +2).

**Comment by andersevenrud** [comment]
> Something tells me that this comes from your index.js file

After a remote session, I discovered that this was the issue.
